### PR TITLE
support specifying multiple target IP's

### LINKED ISSUE #57: allow targetting multiple specific ip's
Hello,
I have a bunch of containers:
```
dockerchaos_metrictank5_1 172.18.0.14
dockerchaos_metrictank3_1 172.18.0.13
dockerchaos_metrictank2_1 172.18.0.11
dockerchaos_metrictank1_1 172.18.0.12
dockerchaos_metrictank4_1 172.18.0.10
dockerchaos_metrictank0_1 172.18.0.9
dockerchaos_graphite_1 172.18.0.7
dockerchaos_jaeger_1 172.18.0.6
dockerchaos_graphitemon_1 172.18.0.8
dockerchaos_kafka_1 172.18.0.5
dockerchaos_statsdaemon_1 172.18.0.3
dockerchaos_grafana_1 172.18.0.4
dockerchaos_cassandra_1 172.18.0.2
```

I want to execute netem loss like for example: 
"block traffic from dockerchaos_metrictank4_1 to dockerchaos_metrictank5_1 and dockerchaos_metrictank3_1 (but not to any of the other containers!) and also block traffic from dockerchaos_metrictank0_1 to dockerchaos_metrictank1_1 and dockerchaos_metrictank5_1"

the example is a bit contrived, but basically the point is that we want to isolate one or more containers from one or more others, and the targets are not necessarily on a consecutive ip range.
in particular, traffic to other containers should remain unaffected, so that we are able to collect monitoring and tracing data to diagnose.
So I need a way to specify a list of ip's that can be targeted. and exactly those ip's and none others. the ability to specify up to two ip ranges would also work, but would be cumbersome to work with. as it's much easier to just specify the list of ip's.

I spent all day messing with the pumba source code and figuring out how to do this but with no luck.
* `man tc-ematch` hints that I can use ipset. but upon further research, looks like this is meant for large/dynamic set of ips, that need to be maintained via the ipset command. this is too complicated and overkill.
*  I also tried the following patch:
```
@@ -352,7 +352,7 @@ func (client dockerClient) startNetemContainerIPFilter(ctx context.Context, c Co
                // 'tc filter add dev <netInterface> protocol ip parent 1:0 prio 1 u32 match ip dst <targetIP> flowid 1:3'
                // See more: http://man7.org/linux/man-pages/man8/tc-netem.8.html
                filterCommand := []string{"filter", "add", "dev", netInterface, "protocol", "ip", "parent", "1:0", "prio", "1",
-                       "u32", "match", "ip", "dst", strings.ToLower(targetIP), "flowid", "1:3"}
+                       "(", "u32", "match", "ip", "dst", "172.18.0.12", "or", "u32", "match", "ip", "dst", "172.18.0.11", ")", "flowid", "1:3"}
                log.Debugf("filterCommand %s", filterCommand)
                return client.tcCommand(ctx, c, filterCommand, tcimage)
        }
```
Note, I run this command from other go code:
```
exec.Command("docker", "run", "--rm", "-v", "/var/run/docker.sock:/var/run/docker.sock", "pumba", "--", "pumba", "--debug", "netem", "--target", "8.7.6.5", "--tc-image", "gaiadocker/iproute2", "--duration", dur, "loss", "--percent", "100", name)
```
the command works fine without target ip filter, but when i try to use my patch it does not.
I thought this would block traffic to those 2 ip's. instead what happens is traffic is *not* affected, but after the duration when the netem is stopped again by pumba, communication fails for some containers but different ip's ! (note that the patch ignores the target argument and uses 2 hardcoded values)

for example, here's the ip listing for each container, and the logs of what happens:
```
~/g/s/g/g/m/chaos ❯❯❯ egrep 'memberlist: Failed UDP ping|netem|filterCommand|CONTAINER' chaos.stdout
CONTAINER dockerchaos_metrictank5_1 172.18.0.14
CONTAINER dockerchaos_metrictank3_1 172.18.0.13
CONTAINER dockerchaos_metrictank2_1 172.18.0.11
CONTAINER dockerchaos_metrictank1_1 172.18.0.12
CONTAINER dockerchaos_metrictank4_1 172.18.0.10
CONTAINER dockerchaos_metrictank0_1 172.18.0.9
CONTAINER dockerchaos_graphite_1 172.18.0.7
CONTAINER dockerchaos_jaeger_1 172.18.0.6
CONTAINER dockerchaos_graphitemon_1 172.18.0.8
CONTAINER dockerchaos_kafka_1 172.18.0.5
CONTAINER dockerchaos_statsdaemon_1 172.18.0.3
CONTAINER dockerchaos_grafana_1 172.18.0.4
CONTAINER dockerchaos_cassandra_1 172.18.0.2
stderr: time="2017-11-14T23:42:21Z" level=info msg="netem: loss random for containers" 
stderr: time="2017-11-14T23:42:21Z" level=info msg="Running netem command '[loss 100.00]' on container 7519e0261fec4ad6c480207f7db499719bfd6396c1ee67273bdcd866f5b67960 with filter 8.7.6.5 for 30s" 
stderr: time="2017-11-14T23:42:21Z" level=info msg="Start netem for container 7519e0261fec4ad6c480207f7db499719bfd6396c1ee67273bdcd866f5b67960 on 'eth0' with command '[loss 100.00]', filter by IP '8.7.6.5'" 
stderr: time="2017-11-14T23:42:21Z" level=debug msg="netemCommand [qdisc add dev eth0 parent 1:1 handle 10: sfq]" 
stderr: time="2017-11-14T23:42:21Z" level=debug msg="netemCommand [qdisc add dev eth0 parent 1:2 handle 20: sfq]" 
stderr: time="2017-11-14T23:42:21Z" level=debug msg="netemCommand [qdisc add dev eth0 parent 1:3 handle 30: netem loss 100.00]" 
stderr: time="2017-11-14T23:42:21Z" level=debug msg="Container Config: {   %!s(bool=false) %!s(bool=false) %!s(bool=false) map[] %!s(bool=false) %!s(bool=false) %!s(bool=false) [] [qdisc add dev eth0 parent 1:3 handle 30: netem loss 100.00] %!s(*container.HealthConfig=<nil>) %!s(bool=false) gaiadocker/iproute2 map[]  [tc] %!s(bool=false)  [] map[com.gaiaadm.pumba.skip:true]  %!s(*int=<nil>) []}" 
stderr: time="2017-11-14T23:42:22Z" level=debug msg="filterCommand [filter add dev eth0 protocol ip parent 1:0 prio 1 ( u32 match ip dst 172.18.0.12 or u32 match ip dst 172.18.0.11 ) flowid 1:3]" 
stderr: time="2017-11-14T23:42:52Z" level=debug msg="Stopping netem after: 30s" 
stderr: time="2017-11-14T23:42:52Z" level=info msg="Stopping netem on container 7519e0261fec4ad6c480207f7db499719bfd6396c1ee67273bdcd866f5b67960" 
stderr: time="2017-11-14T23:42:52Z" level=info msg="Stop netem for container 7519e0261fec4ad6c480207f7db499719bfd6396c1ee67273bdcd866f5b67960 on 'eth0'" 
stdout: metrictank4_1  | 2017/11/14 23:42:53 [DEBUG] memberlist: Failed UDP ping: metrictank5 (timeout reached)
stdout: metrictank2_1  | 2017/11/14 23:42:53 [DEBUG] memberlist: Failed UDP ping: metrictank4 (timeout reached)

```

I will continue trying to figure this out but any help is greatly appreciated, with some input I could save a lot of time.. thanks !

### PR DESCRIPTION
**Pull request by Dieterbe**
we now parse multiple ip's, comma separated.

also: validate ip's early on. previously we would silently ignore ip
parse errors

fix #57 

note: still need to test further, but this shows how i go about it.

### CODE REVIEW

**Comment by Dieterbe** [comment]
did some testing, seems to work well for me. ready for review ! :)

**Comment by alexei-led** [comment]
@Dieterbe  CI build fails, but it's CI bug we are going to fix. Ignore it for now. I will review it manually.

**Comment by alexei-led** [comment]
@Dieterbe there are some test that fails

you can run tests with `go test` or helper script `script/coverage.sh`

p.s.: can you, please also add a test for multiple IPs

Thank you

**Comment by Dieterbe** [comment]
@alexei-led how does it look now? codefresh won't show me the build results unless I sign up, and signing up requires a whole bunch of permissions which i'm not willing to permit.  on my system, `script/coverage.sh` logs some errors, but the same ones as master

**Comment by alexei-led** [comment]
@Dieterbe thank you for the contribution!

**Pull request merged**
