### PR TITLE
avoid self-killing on kubernetes

### PR DESCRIPTION
**Pull request by grosser**
solves https://github.com/gaia-adm/pumba/issues/62

@Dieterbe

### CODE REVIEW

**Comment by grosser** [comment]
did not work :(

**Comment by Dieterbe** [comment]
why are you mentioning me ? i haven't had a problem like this. i used to use my both my own docker image as well as the official one without this problem.

**Comment by grosser** [comment]
mentioned you for code-review :)

so strange that your own image worked for you ... I though this fix would work ... 

I got it running with the label but it still kills itself :/
```
                "com.gaiaadm.pumba": "true",
```

**Comment by Dieterbe** [comment]
to be clear i've just used these images in a local dockre-compose stack, not k8s

**Comment by grosser** [comment]
ah, that might be the difference ... I'll keep digging, no worries :D

**Comment by grosser** [comment]
found it ... good to merge ?

**Pull request merged**
